// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace OneRegister.Data.Entities.MasterCardGems
{
    public partial class CDDActionDV_ListResult
    {
        public int CDDActionDV { get; set; }
        public string EntityCIF { get; set; }
        public string EntityFullName { get; set; }
        public int? EntityID { get; set; }
        public string DVStatusL1 { get; set; }
        public string DVStatusL2 { get; set; }
        public string DVStatus { get; set; }
        public string DocType { get; set; }
        public string DocImg1 { get; set; }
        public string DocImg2 { get; set; }
        public string DVMechanism { get; set; }
        public int? MatchScore { get; set; }
        public DateTime? VeriStartDate { get; set; }
        public DateTime? VeriEndDate { get; set; }
        public string VeriBy { get; set; }
        public string AuditBy { get; set; }
        public string ProcessorID { get; set; }
        public string ProcessorTxnID { get; set; }
        public string VeriRemarks { get; set; }
        public string AuditStatus { get; set; }
        public string AuditRemarks { get; set; }
        public DateTime? xDVDateCreated { get; set; }
        public string xModifiedBy { get; set; }
        public int L1RetryCounter { get; set; }
        public int L1SysError { get; set; }
        public string jsonResultsRaw { get; set; }
    }
}
