// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace OneRegister.Data.Entities.MasterCardGems
{
    public partial class CDDActionID_ListRequestsResult
    {
        public int CDDActionID { get; set; }
        public int EntityID { get; set; }
        public string ProcessorID { get; set; }
        public string ProcessorTxnID { get; set; }
        public string FullName { get; set; }
        public string IdType { get; set; }
        public string IdValue { get; set; }
        public string FaceImgId { get; set; }
        public string RefDoc1ImgId { get; set; }
        public string RefDoc2ImgId { get; set; }
        public int L1RetryCounter { get; set; }
    }
}
