// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace OneRegister.Data.Entities.MasterCardGems
{
    public partial class Channel_ListServicePackagesResult
    {
        public string Channel { get; set; }
        public string ServicePackage { get; set; }
        public string ServiceCode { get; set; }
        public string PackageName { get; set; }
        public decimal? Fee { get; set; }
    }
}
