// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OneRegister.Data.Entities.MasterCardGems
{
    /// <summary>
    /// Table containing list of Business Services/Products, eg: OnePay, OneDebit, eM-ONEi, M1Pay, etc
    /// </summary>
    [Table("CL_BizService", Schema = "Entity")]
    public partial class ClBizService
    {
        public ClBizService()
        {
            ClServicePackage = new HashSet<ClServicePackage>();
        }

        [Key]
        [Column("_Code")]
        [StringLength(32)]
        public string Code { get; set; }
        [Required]
        [StringLength(100)]
        public string ShortName { get; set; }
        [Required]
        [StringLength(300)]
        public string LongName { get; set; }
        [Column("xIsDeleted")]
        public int XIsDeleted { get; set; }

        [InverseProperty("ServiceCodeNavigation")]
        public virtual ICollection<ClServicePackage> ClServicePackage { get; set; }
    }
}