// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OneRegister.Data.Entities.MasterCardGems
{
    /// <summary>
    /// Codelist of possible channels, eg: APPC,APPA,EDCA,...
    /// </summary>
    [Table("CL_Channel", Schema = "Entity")]
    public partial class ClChannel
    {
        public ClChannel()
        {
            Wfforms = new HashSet<Wfforms>();
        }

        public int CodeNum { get; set; }
        [Key]
        [Column("_Code")]
        [StringLength(32)]
        public string Code { get; set; }
        [Required]
        [StringLength(100)]
        public string ShortName { get; set; }
        [Required]
        [StringLength(300)]
        public string LongName { get; set; }
        [Column("xIsDeleted")]
        public int XIsDeleted { get; set; }

        [InverseProperty("ChannelNavigation")]
        public virtual ICollection<Wfforms> Wfforms { get; set; }
    }
}