// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OneRegister.Data.Entities.MasterCardGems
{
    [Table("CL_CountryState", Schema = "Entity")]
    public partial class ClCountryState
    {
        [Key]
        [Column("StateISOCode")]
        [StringLength(10)]
        public string StateIsocode { get; set; }
        [Key]
        [StringLength(2)]
        public string CountryCode { get; set; }
        [Required]
        [StringLength(50)]
        public string StateName { get; set; }
        [StringLength(10)]
        public string StateAbbr { get; set; }

        public virtual ClCountry CountryCodeNavigation { get; set; }
    }
}