// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OneRegister.Data.Entities.MasterCardGems
{
    [Table("CL_FormType", Schema = "OneReg")]
    public partial class ClFormType
    {
        public ClFormType()
        {
            Wfforms = new HashSet<Wfforms>();
        }

        [Key]
        [StringLength(32)]
        public string FormType { get; set; }
        [StringLength(100)]
        public string Descr { get; set; }

        [InverseProperty("FormTypeNavigation")]
        public virtual ICollection<Wfforms> Wfforms { get; set; }
    }
}