// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OneRegister.Data.Entities.MasterCardGems
{
    /// <summary>
    /// Table containing list of Personal Identification Types, eg: MyKad, Passport
    /// </summary>
    [Table("CL_IdType", Schema = "Entity")]
    public partial class ClIdType
    {
        [Key]
        [Column("_Code")]
        [StringLength(32)]
        public string Code { get; set; }
        [Required]
        [StringLength(100)]
        public string ShortName { get; set; }
        [Required]
        [StringLength(300)]
        public string LongName { get; set; }
        [Column("xIsDeleted")]
        public int XIsDeleted { get; set; }
    }
}