// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OneRegister.Data.Entities.MasterCardGems
{
    /// <summary>
    /// Codelist of possible languages, eg: en,bm,th,ar
    /// </summary>
    [Table("CL_Language", Schema = "Entity")]
    public partial class ClLanguage
    {
        [Key]
        [Column("_Code")]
        [StringLength(2)]
        public string Code { get; set; }
        [Required]
        [StringLength(100)]
        public string ShortName { get; set; }
        [Column("xIsDeleted")]
        public int XIsDeleted { get; set; }
    }
}