// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OneRegister.Data.Entities.MasterCardGems
{
    [Table("CL_ServicePackage", Schema = "aml")]
    public partial class ClServicePackage
    {
        [Key]
        [StringLength(32)]
        public string ServiceCode { get; set; }
        [Key]
        [StringLength(32)]
        public string Package { get; set; }
        [StringLength(32)]
        public string ServicePackage { get; set; }
        [Required]
        [StringLength(100)]
        public string PackageName { get; set; }
        [Column(TypeName = "decimal(20, 2)")]
        public decimal? Price { get; set; }
        [StringLength(100)]
        public string Descr { get; set; }
        [Column("xIsDeleted")]
        public int XIsDeleted { get; set; }

        [ForeignKey(nameof(ServiceCode))]
        [InverseProperty(nameof(ClBizService.ClServicePackage))]
        public virtual ClBizService ServiceCodeNavigation { get; set; }
    }
}