// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace OneRegister.Data.Entities.MasterCardGems
{
    public partial class ServicePackage_ListFieldMandatorinessResult
    {
        public string Display { get; set; }
        public string FieldName { get; set; }
        public string FieldCond { get; set; }
        public string FieldGroup { get; set; }
        public string DisplayName { get; set; }
        public string Path { get; set; }
    }
}
