// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace OneRegister.Data.Entities.MasterCardGems
{
    public partial class WFForms_ListResult
    {
        public string FormNo { get; set; }
        public string FormType { get; set; }
        public string FormStatus { get; set; }
        public string Channel { get; set; }
        public string FullName { get; set; }
        public string MobileNo { get; set; }
        public string IdNo { get; set; }
        public string EntityCIF { get; set; }
        public string ListServicePackages { get; set; }
        public DateTime? FormDateCreated { get; set; }
        public string xCreatedBy { get; set; }
        public string OrgId { get; set; }
        public string Remarks { get; set; }
        public int? SubmissionCount { get; set; }
    }
}
