// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OneRegister.Data.Entities.MasterCardGems
{
    [Table("WFInstance", Schema = "OneReg")]
    public partial class Wfinstance
    {
        public Wfinstance()
        {
            Wfforms = new HashSet<Wfforms>();
        }

        [Key]
        [Column("WFInstanceID")]
        public int WfinstanceId { get; set; }
        [Required]
        [Column("WFType")]
        [StringLength(32)]
        public string Wftype { get; set; }
        public int Step { get; set; }
        [StringLength(1)]
        public string Status { get; set; }

        [InverseProperty("Wfinstance")]
        public virtual ICollection<Wfforms> Wfforms { get; set; }
    }
}